version: "3"

services:
  goapp:
    build: .
    platform: linux/amd64
    container_name: goapp
    volumes:
      - .:/app
    ports:
      - 8080:8080
    command: go run cmd/walletcore/main.go

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wallet
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql:/var/lib/mysql
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./scripts/data.sql:/docker-entrypoint-initdb.d/2.sql
