version: '3'

services:
  balanceapp:
    build: .
    platform: linux/amd64
    container_name: balance-service
    volumes:
      - .:/app
    ports:
      - 3003:3003
    command: bash -c "npm install && npm run start:dev"

  balancedb:
    image: mysql:5.7
    platform: linux/amd64
    container_name: balance-db
    environment:
      MYSQL_DATABASE: wallet
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .docker/mysql:/var/lib/mysql
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./scripts/data.sql:/docker-entrypoint-initdb.d/2.sql
